#encoding:utf-8
"""
Django settings for EWP_OMS project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import ConfigParser


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w+zynb*q9pp#jl2ess*7o*-6o!ogk+skue!sov)#vwt)td)%gq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    # 'grappelli',
    # 'filebrowser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CMDB',
    'SALT',
    'ZABBIX',
    'COBBER',
    'pagination',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
     'pagination.middleware.PaginationMiddleware',
)

ROOT_URLCONF = 'EWP_OMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EWP_OMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

cf = ConfigParser.ConfigParser()
cf.read("EWP_OMS/config.ini")
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': cf.get("db","name"),
        'USER': cf.get("db","user"),
        'PASSWORD':cf.get("db","pass"),
        'HOST': cf.get("db","host"),
        'PORT': cf.get("db","port"),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh_cn'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
# STATIC_ROOT = ( BASE_DIR + '/static')
STATIC_URL = '/static/'
STATICFILES_DIRS = ( BASE_DIR + '/static',)
LOGIN_URL = '/auth/login/'

# UPLOADS_ROOT = ( BASE_DIR + '/media')

# from filebrowser.sites import site
# site.directory = "media/"

MEDIA_ROOT = ( BASE_DIR + '/media')
MEDIA_URL = '/media/'
FILE_FORMAT=['.conf','.sls','.ini','.txt','.sh','.perl','.repo','.cf','config','.py','.cfg','']
